# Site settings
title: Moritz Böhmecke-Schwafert
SEOTitle: Moritz Böhmecke-Schwafert
header-img: img/header.jpg
email: moritzboehmecke@gmail.com
description: "Postdoctoral Research and Manager"
keyword: "Digital Innovation, Economics, Economist, Macroeconomics, Innovation, Digitization, Blockchain, Sustainability, Sustainable Innovation, Circular Economy, Economic Development, Sustainable Development, Trade, Global Value Chains, Distributed ledger Technologies"
url: "https://www.böhmecke-schwafert.eu"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future daty
future: true

# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    MoritzBS
twitter_username:   MoritzBS
#facebook_username:  huxpro
linkedin_username:  MoritzBS #firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: DE



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Postdoctoral Researcher and Lecturer at TU Berlin, Ph.D in Economics, Managing Consultant at IBM. Research at the intersection of digital innovation and development."
sidebar-avatar: /img/mo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



 Links
friends: [
    {
         title: "My TU Website",
         href: "https://www.tu.berlin/index.php?id=49755"
     },{
       title: "My Academic CV",
        href: "https://www.dropbox.com/s/6w2wt3bg3emj5t0/Academic_CV_Moritz_B%C3%B6hmecke-Schwafert.pdf?dl=0"
    },{
        title: "My Google Scholar Profile",
        href: "https://scholar.google.com/citations?user=JJ_BLw0AAAAJ&hl=en"
    },{
        title: "My ResearchGate Profile",
        href: "https://www.researchgate.net/profile/Moritz-Boehmecke-Schwafert"
    #},{
     #   title: "Ebn's Blog",
      #  href: "http://ebnbin.com/"
    #},{
     #   title: "SmdCn's Blog",
      #  href: "http://blog.smdcn.net"
    #},{
     #   title: "JiyinYiyong",
      #  href: "http://tiye.me/"
    #},{
     #   title: "David's Game",
      #  href: "https://www.ruoyaowu.com/"
    #},{
     #   title: "DHong Say",
      #  href: "http://dhong.co"
    #},{
     #   title: "尹峰以为",
      #  href: "http://ingf.github.io/"
    }
]
